/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LevelScore = IDL.Record({
  'minigameScore' : IDL.Nat,
  'levelIndex' : IDL.Nat,
  'passed' : IDL.Bool,
});
export const GameSave = IDL.Record({
  'scores' : IDL.Vec(LevelScore),
  'relationshipScore' : IDL.Nat,
  'currentLevel' : IDL.Nat,
  'lastSaved' : IDL.Int,
  'completedLevels' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  'loadGame' : IDL.Func([], [IDL.Opt(GameSave)], ['query']),
  'resetGame' : IDL.Func([], [IDL.Bool], []),
  'saveGame' : IDL.Func([GameSave], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LevelScore = IDL.Record({
    'minigameScore' : IDL.Nat,
    'levelIndex' : IDL.Nat,
    'passed' : IDL.Bool,
  });
  const GameSave = IDL.Record({
    'scores' : IDL.Vec(LevelScore),
    'relationshipScore' : IDL.Nat,
    'currentLevel' : IDL.Nat,
    'lastSaved' : IDL.Int,
    'completedLevels' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    'loadGame' : IDL.Func([], [IDL.Opt(GameSave)], ['query']),
    'resetGame' : IDL.Func([], [IDL.Bool], []),
    'saveGame' : IDL.Func([GameSave], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };